apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  labels:
    app: pgadmin
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/pgadmin/pgadm
  persistentVolumeReclaimPolicy: Retain
